Repository instana/openapi, pull requests merged in 2022-05, with the labels that each got.

#42 Add more description for Synthetic OpenAPIs
  spec/descriptions/createSyntheticTest.md
  spec/descriptions/tagSyntheticResults.md
  spec/descriptions/tagSyntheticSettings.md
Labels: Review & Merge

#43 add instana community link as first item into info
  spec/descriptions/info.md
Labels: Review & Merge

#39 [R224] Add docs for PUT and DELETE of custom-event-spec
  spec/descriptions/deleteCustomEventSpecification.md
  spec/descriptions/postCustomEventSpecification.md
  spec/descriptions/putCustomEventSpecification.md
Labels: enhancement, pending-next-release, Review & Merge

#46 Add description for getting a list of Synthetic test results OpenAPI
  spec/descriptions/tagSyntheticResults.md
  spec/descriptions/tagSyntheticSettings.md
Labels: enhancement, Review & Merge

#45 Update open API docs for deprecated custom events
  spec/descriptions/postCustomEventSpecification.md
  spec/descriptions/putCustomEventSpecification.md
Labels: good first issue, pending-next-release
