Repository instana/openapi, pull requests merged in 2022-03, with the labels that each got.

#35 Describe filterEventUpdates param of Event API
  spec/descriptions/getEvents.md
Labels: enhancement, pending-next-release

#36 Add remark about eventual consistency
  spec/descriptions/getEvents.md
Labels: enhancement

#37 Add description for getEventsByIds
  spec/descriptions/getEventsByIds.md
Labels: Review & Merge

#34 [Release 221] document timeframe adjustment in API doc
  spec/descriptions/tagApplicationAnalyze.md
  spec/descriptions/tagApplicationMetrics.md
Labels: enhancement, pending-next-release
