Repository instana/openapi, pull requests merged in 2023-02, with the labels that each got.

#66 Add description for getLocationSummaryList API
  spec/descriptions/tagSyntheticResults.md
Labels: enhancement, Review & Merge

#67 114359 - Adding description for synthetic test PATCH API
  spec/descriptions/patchSyntheticTest.md
Labels: enhancement

#68 Add descriptions for Synth SA fields, create and update
  spec/descriptions/createSyntheticAlertConfig.md
  spec/descriptions/createSyntheticTest.md
  spec/descriptions/patchSyntheticTest.md
  spec/descriptions/postCustomEventSpecification.md
  spec/descriptions/putCustomEventSpecification.md
  spec/descriptions/tagSyntheticAlertConfiguration.md
  spec/descriptions/updateSyntheticAlertConfig.md
Labels: Review & Merge
